server: "hub.lambdatest.com"
user: "LT_USERNAME"
key: "LT_ACCESS_KEY"

common_caps:
  "build": "RSpec Selenium Demo"

browser_caps:
  -
    "browserName": "chrome"
    "browserVersion": "latest"
    "platformName": "Windows 11"
    "LT:Options":
      "selenium_version": "4.27.0"
      "name": "RSpec HyperTest Test"
      "build": "RSpec HyperTest Demo"
      "w3c": true